// Proxy server (same for all matched rules)
const proxy = "PROXY 127.0.0.1:14622; PROXY 192.168.2.4:7891";
const direct = "DIRECT";

// ========== 1. Exact domain matching (hash table, O(1)) ==========
const DOMAIN = {
    "cn.bing.com": direct,
    "damag.net": proxy,
    "www.tokyotosho.info": proxy,
    "www.torrentdownloads.pro": proxy,
    "www.asmrgay.com": proxy,
    "aistudio.google.com": proxy,
    "api.githubcopilot.com": proxy,
    "api.groq.com": proxy,
    "api.together.xyz": proxy,
    "bard.google.com": proxy,
    "console.groq.com": proxy,
    "copilot-proxy.githubusercontent.com": proxy,
    "gemini.google.com": proxy,
    "generativelanguage.googleapis.com": proxy,
    "notebooklm.google.com": proxy,
    "sydney.bing.com": proxy,
    "atv-ps.amazon.com": proxy,
    "avodmp4s3ww-a.akamaihd.net": proxy,
    "d1v5ir2lpwr8os.cloudfront.net": proxy,
    "d1xfray82862hr.cloudfront.net": proxy,
    "d22qjgkvxw22r6.cloudfront.net": proxy,
    "d25xi40x97liuc.cloudfront.net": proxy,
    "d27xxe7juh1us6.cloudfront.net": proxy,
    "d3196yreox78o9.cloudfront.net": proxy,
    "dmqdd6hw24ucf.cloudfront.net": proxy,
    "ktpx.amazon.com": proxy,
    "gspe1-ssl.ls.apple.com": proxy,
    "np-edge.itunes.apple.com": proxy,
    "play-edge.itunes.apple.com": proxy,
    "aod-dash-uk-live.akamaized.net": proxy,
    "aod-hls-uk-live.akamaized.net": proxy,
    "vod-dash-uk-live.akamaized.net": proxy,
    "vod-thumb-uk-live.akamaized.net": proxy,
    "bahamut.akamaized.net": proxy,
    "gamer-cds.cdn.hinet.net": proxy,
    "gamer2-cds.cdn.hinet.net": proxy,
    "d151l6v8er5bdm.cloudfront.net": proxy,
    "cdn.registerdisney.go.com": proxy,
    "bcbolt446c5271-a.akamaihd.net": proxy,
    "content.jwplatform.com": proxy,
    "edge.api.brightcove.com": proxy,
    "videos-f.jwpsrv.com": proxy,
    "44wilhpljf.execute-api.ap-southeast-1.amazonaws.com": proxy,
    "bcbolthboa-a.akamaihd.net": proxy,
    "cf-images.ap-southeast-1.prod.boltdns.net": proxy,
    "dai3fd1oh325y.cloudfront.net": proxy,
    "hboasia1-i.akamaihd.net": proxy,
    "hboasia2-i.akamaihd.net": proxy,
    "hboasia3-i.akamaihd.net": proxy,
    "hboasia4-i.akamaihd.net": proxy,
    "hboasia5-i.akamaihd.net": proxy,
    "hboasialive.akamaized.net": proxy,
    "hbogoprod-vod.akamaized.net": proxy,
    "hbolb.onwardsmg.com": proxy,
    "hbounify-prod.evergent.com": proxy,
    "players.brightcove.net": proxy,
    "s3-ap-southeast-1.amazonaws.com": proxy,
    "itvpnpmobile-a.akamaihd.net": proxy,
    "kktv-theater.kk.stream": proxy,
    "theater-kktv.cdn.hinet.net": proxy,
    "litvfreemobile-hichannel.cdn.hinet.net": proxy,
    "d3c7rimkq79yfu.cloudfront.net": proxy,
    "d349g9zuie06uo.cloudfront.net": proxy,
    "mytvsuperlimited.hb.omtrdc.net": proxy,
    "mytvsuperlimited.sc.omtrdc.net": proxy,
    "netflix.com.edgesuite.net": proxy,
    "hamifans.emome.net": proxy,
    "api.viu.now.com": proxy,
    "d1k2us671qcoau.cloudfront.net": proxy,
    "d2anahhhmp1ffz.cloudfront.net": proxy,
    "dfp6rglgjqszk.cloudfront.net": proxy,
    "youtubei.googleapis.com": proxy,
    "yt3.ggpht.com": proxy,
    "surrit.com": proxy,
    "music.youtube.com": proxy,
    "d1q6f0aelx0por.cloudfront.net": proxy,
    "d2wy8f7a9ursnm.cloudfront.net": proxy,
    "d36jcksde1wxzq.cloudfront.net": proxy,
    "steambroadcast.akamaized.net": proxy,
    "steamcommunity-a.akamaihd.net": proxy,
    "steamstore-a.akamaihd.net": proxy,
    "steamusercontent-a.akamaihd.net": proxy,
    "steamuserimages-a.akamaihd.net": proxy,
    "steampipe.akamaized.net": proxy,
};

// ========== 2. Direct suffix matching ==========
const DOMAIN_SUFFIX_DIRECT = [
    "finalize.top",
    ".cn",
]

// ========== 3. Direct keyword matching ==========
const DOMAIN_KEYWORD_DIRECT = [
]

// ========== 4. Suffix matching (500+ entries -> single regex) ==========
const DOMAIN_SUFFIX_PROXY = [
    "nyaa.si",
    "e-hentai.org",
    "onejav.com",
    "gdstudio.xyz",
    "z-lib.fm",
    "thetvdb.com",
    "tdesktop.com",
    "telegra.ph",
    "telegram.me",
    "telegram.org",
    "telesco.pe",
    "edgedatg.com",
    "go.com",
    "ai.azure.com",
    "anthropic.com",
    "auth0.com",
    "bard.google.com",
    "chatgpt.com",
    "claude.ai",
    "claude.com",
    "claudeusercontent.com",
    "client-api.arkoselabs.com",
    "copilot.cloud.microsoft",
    "copilot.microsoft.com",
    "cursor.com",
    "cursor.sh",
    "events.statsigapi.net",
    "featuregates.org",
    "gemini.google.com",
    "grazie.ai",
    "grazie.aws.intellij.net",
    "identrust.com",
    "intercom.io",
    "intercomcdn.com",
    "jetbrains.ai",
    "makersuite.google.com",
    "meta.ai",
    "mistral.ai",
    "oaistatic.com",
    "oaiusercontent.com",
    "openai.com",
    "openaiapi-site.azureedge.net",
    "perplexity.ai",
    "sora.com",
    "x.ai",
    "abema.io",
    "abema.tv",
    "ameba.jp",
    "hayabusa.io",
    "c4assets.com",
    "channel4.com",
    "aboutamazon.com",
    "aiv-cdn.net",
    "aiv-delivery.net",
    "amazon.jobs",
    "amazontools.com",
    "amazontours.com",
    "amazonuniversity.jobs",
    "amazonvideo.com",
    "media-amazon.com",
    "pv-cdn.net",
    "seattlespheres.com",
    "tv.apple.com",
    "bbc.co",
    "bbc.co.uk",
    "bbc.com",
    "bbc.net.uk",
    "bbcfmt.hs.llnwd.net",
    "bbci.co",
    "bbci.co.uk",
    "bidi.net.uk",
    "bahamut.com.tw",
    "gamer.com.tw",
    "d151l6v8er5bdm.cloudfront.net",
    "d1sgwhnao7452x.cloudfront.net",
    "dazn-api.com",
    "dazn.com",
    "dazndn.com",
    "dcblivedazn.akamaized.net",
    "indazn.com",
    "indaznlab.com",
    "sentry.io",
    "deezer.com",
    "dzcdn.net",
    "disco-api.com",
    "discovery.com",
    "uplynk.com",
    "adobedtm.com",
    "bam.nr-data.net",
    "bamgrid.com",
    "braze.com",
    "cdn.optimizely.com",
    "cdn.registerdisney.go.com",
    "cws.conviva.com",
    "d9.flashtalking.com",
    "disney-plus.net",
    "disney-portal.my.onetrust.com",
    "disney.demdex.net",
    "disney.my.sentry.io",
    "disneyplus.bn5x.net",
    "disneyplus.com",
    "disneyplus.com.ssl.sc.omtrdc.net",
    "disneystreaming.com",
    "dssott.com",
    "execute-api.us-east-1.amazonaws.com",
    "js-agent.newrelic.com",
    "encoretvb.com",
    "fox.com",
    "foxdcg.com",
    "uplynk.com",
    "hbo.com",
    "hbogo.com",
    "hbomax.com",
    "hbomaxcdn.com",
    "hbonow.com",
    "hboasia.com",
    "hbogoasia.com",
    "hbogoasia.hk",
    "5itv.tv",
    "ocnttv.com",
    "cws-hulu.conviva.com",
    "hulu.com",
    "hulu.hb.omtrdc.net",
    "hulu.sc.omtrdc.net",
    "huluad.com",
    "huluim.com",
    "hulustream.com",
    "happyon.jp",
    "hjholdings.jp",
    "hulu.jp",
    "prod.hjholdings.tv",
    "streaks.jp",
    "yb.uncn.jp",
    "itv.com",
    "itvstatic.com",
    "iwara.tv",
    "joox.com",
    "japonx.com",
    "japonx.net",
    "japonx.tv",
    "japonx.vip",
    "japronx.com",
    "japronx.net",
    "japronx.tv",
    "japronx.vip",
    "kfs.io",
    "kkbox.com",
    "kkbox.com.tw",
    "kktv.com.tw",
    "kktv.me",
    "litv.tv",
    "d3c7rimkq79yfu.cloudfront.net",
    "linetv.tw",
    "profile.line-scdn.net",
    "channel5.com",
    "my5.tv",
    "mytvsuper.com",
    "tvb.com",
    "fast.com",
    "netflix.com",
    "netflix.net",
    "netflixdnstest0.com",
    "netflixdnstest1.com",
    "netflixdnstest2.com",
    "netflixdnstest3.com",
    "netflixdnstest4.com",
    "netflixdnstest5.com",
    "netflixdnstest6.com",
    "netflixdnstest7.com",
    "netflixdnstest8.com",
    "netflixdnstest9.com",
    "nflxext.com",
    "nflximg.com",
    "nflximg.net",
    "nflxso.net",
    "nflxvideo.net",
    "dmc.nico",
    "nicovideo.jp",
    "nimg.jp",
    "biggggg.com",
    "mudvod.tv",
    "nbys.tv",
    "nbys1.tv",
    "nbyy.tv",
    "newpppp.com",
    "nivod.tv",
    "nivodi.tv",
    "nivodz.com",
    "vod360.net",
    "haiwaikan.com",
    "iole.tv",
    "olehd.com",
    "olelive.com",
    "olevod.com",
    "olevod.io",
    "olevod.tv",
    "olevodtv.com",
    "auth0.com",
    "challenges.cloudflare.com",
    "chatgpt.com",
    "client-api.arkoselabs.com",
    "events.statsigapi.net",
    "featuregates.org",
    "identrust.com",
    "intercom.io",
    "intercomcdn.com",
    "oaistatic.com",
    "oaiusercontent.com",
    "openai.com",
    "openaiapi-site.azureedge.net",
    "sentry.io",
    "stripe.com",
    "pbs.org",
    "pandora.com",
    "phncdn.com",
    "phprcdn.com",
    "pornhub.com",
    "pornhubpremium.com",
    "qobuz.com",
    "p-cdn.us",
    "sndcdn.com",
    "soundcloud.com",
    "pscdn.co",
    "scdn.co",
    "spoti.fi",
    "spotify.com",
    "spotifycdn.com",
    "spotifycdn.net",
    "tidal-cms.s3.amazonaws.com",
    "tidal.com",
    "tidalhifi.com",
    "skyking.com.tw",
    "byteoversea.com",
    "ibytedtos.com",
    "ipstatp.com",
    "muscdn.com",
    "musical.ly",
    "tik-tokapi.com",
    "tiktok.com",
    "tiktokcdn.com",
    "tiktokv.com",
    "ext-twitch.tv",
    "jtvnw.net",
    "ttvnw.net",
    "twitch-ext.rootonline.de",
    "twitch.tv",
    "twitchcdn.net",
    "cognito-identity.us-east-1.amazonaws.com",
    "d1k2us671qcoau.cloudfront.net",
    "d2anahhhmp1ffz.cloudfront.net",
    "dfp6rglgjqszk.cloudfront.net",
    "mobileanalytics.us-east-1.amazonaws.com",
    "viu.com",
    "viu.now.com",
    "viu.tv",
    "googlevideo.com",
    "gvt2.com",
    "withyoutube.com",
    "youtu.be",
    "youtube-nocookie.com",
    "youtube.com",
    "youtubeeducation.com",
    "youtubegaming.com",
    "youtubekids.com",
    "yt.be",
    "ytimg.com",
    "1password.com",
    "adguard.org",
    "bit.no.com",
    "btlibrary.me",
    "cloudcone.com",
    "dubox.com",
    "gameloft.com",
    "garena.com",
    "hoyolab.com",
    "inoreader.com",
    "ip138.com",
    "linkedin.com",
    "myteamspeak.com",
    "notion.so",
    "ping.pe",
    "reddit.com",
    "teddysun.com",
    "tumbex.com",
    "twdvd.com",
    "unsplash.com",
    "buzzsprout.com",
    "eu",
    "hk",
    "jp",
    "kr",
    "sg",
    "tw",
    "uk",
    "us",
    "4sqi.net",
    "a248.e.akamai.net",
    "adobedtm.com",
    "ampproject.org",
    "android.com",
    "aolcdn.com",
    "apkmirror.com",
    "apkpure.com",
    "app-measurement.com",
    "appspot.com",
    "archive.org",
    "armorgames.com",
    "aspnetcdn.com",
    "awsstatic.com",
    "azureedge.net",
    "azurewebsites.net",
    "bandwagonhost.com",
    "bing.com",
    "bkrtx.com",
    "blogcdn.com",
    "blogger.com",
    "blogsmithmedia.com",
    "blogspot.com",
    "blogspot.hk",
    "blogspot.jp",
    "bloomberg.cn",
    "bloomberg.com",
    "box.com",
    "cachefly.net",
    "cdnst.net",
    "cloudfront.net",
    "comodoca.com",
    "daum.net",
    "deskconnect.com",
    "disqus.com",
    "disquscdn.com",
    "dropbox.com",
    "dropboxapi.com",
    "dropboxstatic.com",
    "dropboxusercontent.com",
    "duckduckgo.com",
    "edgecastcdn.net",
    "edgekey.net",
    "edgesuite.net",
    "eurekavpt.com",
    "fastmail.com",
    "firebaseio.com",
    "flickr.com",
    "flipboard.com",
    "gfx.ms",
    "gongm.in",
    "hulu.com",
    "id.heroku.com",
    "io.io",
    "issuu.com",
    "ixquick.com",
    "jtvnw.net",
    "kat.cr",
    "kik.com",
    "kobo.com",
    "kobobooks.com",
    "licdn.com",
    "live.net",
    "livefilestore.com",
    "llnwd.net",
    "macrumors.com",
    "medium.com",
    "mega.nz",
    "megaupload.com",
    "messenger.com",
    "netdna-cdn.com",
    "nintendo.net",
    "nsstatic.net",
    "nytstyle.com",
    "overcast.fm",
    "openvpn.net",
    "periscope.tv",
    "pinimg.com",
    "pinterest.com",
    "potato.im",
    "prfct.co",
    "pscp.tv",
    "quora.com",
    "resilio.com",
    "sfx.ms",
    "shadowsocks.org",
    "slack-edge.com",
    "smartdnsproxy.com",
    "sndcdn.com",
    "soundcloud.com",
    "startpage.com",
    "staticflickr.com",
    "symauth.com",
    "symcb.com",
    "symcd.com",
    "textnow.com",
    "textnow.me",
    "thefacebook.com",
    "thepiratebay.org",
    "torproject.org",
    "trustasiassl.com",
    "tumblr.co",
    "tumblr.com",
    "tvb.com",
    "txmblr.com",
    "v2ex.com",
    "vimeo.com",
    "vine.co",
    "vox-cdn.com",
    "amazon.co.jp",
    "amazon.com",
    "amazonaws.com",
    "bbc.co",
    "bbc.com",
    "claude.ai",
    "anthropic.com",
    "apache.org",
    "docker.com",
    "docker.io",
    "elastic.co",
    "elastic.com",
    "gcr.io",
    "gitlab.com",
    "gitlab.io",
    "jitpack.io",
    "maven.org",
    "medium.com",
    "mvnrepository.com",
    "quay.io",
    "reddit.com",
    "redhat.com",
    "sonatype.org",
    "sourcegraph.com",
    "spring.io",
    "spring.net",
    "stackoverflow.com",
    "compose-spec.io",
    "docker.com",
    "docker.io",
    "dockerhub.com",
    "discord.co",
    "discord.com",
    "discord.gg",
    "discord.media",
    "discordapp.com",
    "discordapp.net",
    "facebook.com",
    "fb.com",
    "fb.me",
    "fbcdn.com",
    "fbcdn.net",
    "github.com",
    "github.io",
    "githubapp.com",
    "githubassets.com",
    "githubusercontent.com",
    "1e100.net",
    "2mdn.net",
    "app-measurement.net",
    "c.gle",
    "g.co",
    "ggpht.com",
    "goo.gl",
    "googleapis.cn",
    "googleapis.com",
    "gstatic.cn",
    "gstatic.com",
    "gvt0.com",
    "gvt1.com",
    "gvt2.com",
    "gvt3.com",
    "xn--ngstr-lra8j.com",
    "youtu.be",
    "youtube-nocookie.com",
    "youtube.com",
    "yt.be",
    "ytimg.com",
    "cdninstagram.com",
    "instagram.com",
    "instagr.am",
    "iwara.tv",
    "kakao.com",
    "kakao.co.kr",
    "kakaocdn.net",
    "lin.ee",
    "line-apps.com",
    "line-cdn.net",
    "line-scdn.net",
    "line.me",
    "line.naver.jp",
    "nhncorp.jp",
    "openai.com",
    "challenges.cloudflare.com",
    "livefilestore.com",
    "oneclient.sfx.ms",
    "onedrive.com",
    "onedrive.live.com",
    "photos.live.com",
    "skydrive.wns.windows.com",
    "spoprod-a.akamaihd.net",
    "storage.live.com",
    "storage.msn.com",
    "microsoftpersonalcontent.com",
    "8teenxxx.com",
    "ahcdn.com",
    "bcvcdn.com",
    "bongacams.com",
    "chaturbate.com",
    "dditscdn.com",
    "livejasmin.com",
    "phncdn.com",
    "phprcdn.com",
    "pornhub.com",
    "pornhubpremium.com",
    "rdtcdn.com",
    "redtube.com",
    "sb-cd.com",
    "spankbang.com",
    "t66y.com",
    "xhamster.com",
    "xnxx-cdn.com",
    "xnxx.com",
    "xvideos-cdn.com",
    "xvideos.com",
    "ypncdn.com",
    "pixiv.net",
    "pximg.net",
    "fanbox.cc",
    "amplitude.com",
    "firebaseio.com",
    "hockeyapp.net",
    "readdle.com",
    "smartmailcloud.com",
    "fanatical.com",
    "humblebundle.com",
    "underlords.com",
    "valvesoftware.com",
    "playartifact.com",
    "steam-chat.com",
    "steamcommunity.com",
    "steamgames.com",
    "steampowered.com",
    "steamserver.net",
    "steamstatic.com",
    "steamstat.us",
    "tap.io",
    "taptap.tw",
    "twitch.tv",
    "ttvnw.net",
    "jtvnw.net",
    "t.co",
    "twimg.co",
    "twimg.com",
    "twimg.org",
    "x.com",
    "t.me",
    "tdesktop.com",
    "telegra.ph",
    "telegram.me",
    "telegram.org",
    "telesco.pe",
    "terabox.com",
    "teraboxcdn.com",
    "mediawiki.org",
    "wikibooks.org",
    "wikidata.org",
    "wikileaks.org",
    "wikimedia.org",
    "wikinews.org",
    "wikipedia.org",
    "wikiquote.org",
    "wikisource.org",
    "wikiversity.org",
    "wikivoyage.org",
    "wiktionary.org",
    "zoom.us",
    "zoomgov.com",
    "neulion.com",
    "icntv.xyz",
    "flzbcdn.xyz",
    "ocnttv.com",
    "vikacg.com",
    "picjs.xyz",

    "asuswrt-merlin.net",
    "immortalwrt.org",
    "huggingface.co",
];

// ========== 5. Keyword matching (50+ entries -> single regex) ==========
const DOMAIN_KEYWORD_PROXY = [
    "claude",
    "openai",
    "abematv.akamaized.net",
    "avoddashs",
    "bbcfmt",
    "uk-live",
    "voddazn",
    "hbogoasia",
    "jooxweb-api",
    "japonx",
    "japronx",
    "nowtv100",
    "rthklive",
    "apiproxy-device-prod-nlb-",
    "dualstack.apiproxy-",
    "netflixdnstest",
    "nivod",
    "olevod",
    "openai",
    "-spotify-",
    "spotify.com",
    "tiktokcdn",
    "ttvnw",
    "youtube",
    "1e100",
    "abema",
    "appledaily",
    "avtb",
    "beetalk",
    "blogspot",
    "dropbox",
    "facebook",
    "fbcdn",
    "github",
    "gmail",
    "google",
    "instagram",
    "porn",
    "sci-hub",
    "spotify",
    "telegram",
    "twitter",
    "whatsapp",
    "youtube",
    "uk-live",
    "1drv",
    "onedrive",
    "skydrive",
    "porn",
    "missav",
    "ttvnw",
];



// ===========================================================================================

// Escape regex special characters
const escapeRegex = str => str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

// Build a regex that matches exact suffix or ".suffix" at the end of hostname
// direct regex
const suffixPatternDirect = DOMAIN_SUFFIX_DIRECT.map(escapeRegex).join('|');
// const keywordPatternDirect = DOMAIN_KEYWORD_DIRECT.map(escapeRegex).join('|');
const directRegexParts = [
    `(?:^|\\.)(?:${suffixPatternDirect})$`,
    // keywordPatternDirect
];

const DIRECT_REGEX = new RegExp(directRegexParts.join('|'), 'i');

// proxy regex
const suffixPatternProxy = DOMAIN_SUFFIX_PROXY.map(escapeRegex).join('|');
const keywordPatternProxy = DOMAIN_KEYWORD_PROXY.map(escapeRegex).join('|');
const proxyRegexParts = [
    `(?:^|\\.)(?:${suffixPatternProxy})$`,
    keywordPatternProxy
];

const PROXY_REGEX = new RegExp(proxyRegexParts.join('|'), 'i');

// ========== Main PAC function ==========
function FindProxyForURL(url, host) {
    // 1. Exact match (hash table)
    if (DOMAIN.hasOwnProperty(host)) {
        return DOMAIN[host];
    }

    // 2. Direct match (single regex test)
    if (DIRECT_REGEX.test(host)) {
        return direct;
    }

    // 3. Pproxy match (single regex test)
    if (PROXY_REGEX.test(host)) {
        return proxy;
    }

    // Default: direct connection
    return direct;
}
